#!/usr/bin/bash



Color_Off="\[\033[0m\]"
BYellow="\[\033[1;33m\]"
Green="\[\033[0;32m\]"
IRed="\[\033[1;91m\]"


function __get_prompt() {
    git branch &>/dev/null 2>&1
    if [ $? -eq 0 ]; then
        # If in git repo
        local prefix=" $(__get_git_prompt_label)$(__get_stash_count_prompt)";
    else
        local prefix=" ${Green}${USER}@${HOSTNAME}";
    fi
    echo -e "${prefix} ${BYellow}$(basename $(pwd))${Color_Off}$ "
}


function __get_git_prompt_label() {
    git status | grep "nothing to commit" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        # Clean repository
        echo "${Green}$(__git_ps1 '(%s)')${Color_Off}"
    else
        # Uncommitted changes
        echo "${IRed}$(__git_ps1 '{%s}')${Color_Off}"
    fi
}


function __get_stash_count_prompt() {
    local stash_count=$(git stash list | wc -l)
    if [ ${stash_count} -ne 0 ] ; then
        echo "${IRed}[$stash_count]${Color_Off}"
    fi
}


function __set_bash_prompt() {
    PS1=$(__get_prompt)
}

PROMPT_COMMAND=__set_bash_prompt

