#!/usr/bin/bash

source ~/.rc_files/prompt

umask 002
export SHELL=$(type -p bash)
export LESS="-R $LESS"
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && source /usr/share/bash-completion/bash_completion
export CDPATH=~/git/ # Allows you to 'cd <repo>' from anywhere!
export EDITOR=vim
export PYTHONSTARTUP=~/.rc_files/python_startup.py
export PIP_USER=true # So pip installs to ~/.local/lib
export JAVA_HOME=/usr/lib/jvm/java-8-oracle

# Cause Elasticsearch uses too much God damn memory!
ES_JAVA_OPTS="-Xms1g -Xmx1g"

# Set DISPLAY variable
XSERVER=$(who am i | awk '{print $NF}' | tr -d ')''(' )
if [ -z "${DISPLAY}" ]; then
    if [[ -z "${XSERVER}" || "${XSERVER}" == $(hostname) || "${XSERVER}" == "unix" ]]; then
        DISPLAY=":0.0" # Display on local host.
    else
        DISPLAY=${XSERVER}:0.0 # Display on remote host.
    fi
fi
export DISPLAY

# Android development stuff
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:~/.yarn/bin
export PATH=$PATH:~/.local/bin
