#!/usr/bin/bash

# Set my coloured prompt
Color_Off="\[\033[0m\]"       # Text Reset
BYellow="\[\033[1;33m\]"      # Bold yellow
Green="\[\033[0;32m\]"        # Green
UserName="\u"
Hostname="\h"
PathShort="\W"

source ~/.rc_files/prompt

umask 002
export SHELL=$(type -p bash)
export LESS="-R $LESS"
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && source /usr/share/bash-completion/bash_completion
export CDPATH=~/git/
export EDITOR=vim
export PYTHONSTARTUP=~/.rc_files/python_startup.py
export PIP_USER=true # So pip installs to ~/.local/lib
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
PERL_MB_OPT="--install_base \"/home/edarder/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/edarder/perl5"; export PERL_MM_OPT;

# Cause Elasticsearch uses too much God damn memory!
ES_JAVA_OPTS="-Xms1g -Xmx1g"

# Set DISPLAY variable
XSERVER=$(who am i | awk '{print $NF}' | tr -d ')''(' )
if [ -z "${DISPLAY}" ]; then
    if [[ -z "${XSERVER}" || "${XSERVER}" == $(hostname) || "${XSERVER}" == "unix" ]]; then
        DISPLAY=":0.0" # Display on local host.
    else
        DISPLAY=${XSERVER}:0.0 # Display on remote host.
    fi
fi
export DISPLAY

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:~/.yarn/bin
