#!/usr/bin/bash

# Finds text anywhere within the directory you're in
function g() {
    if [[ $# != 1 ]] ; then
        echo  -e "Usage: $FUNCNAME <pattern>\n" \
                 " Recursively searches for pattern given (case insensitive)"
        return 1
    fi
    grep --color=always -rin "$*" *

}

# Find a file within the directory you're in
function f() {
    if [[ $# != 1 ]] ; then
        echo -e "Usage: $FUNCNAME <pattern>\n" \
                " Finds file name with pattern from the current directory (case insensitive)"
        return 1
    fi

    find . -iname "$*"
}
